version: "2"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/recode
    expose:
      - "3000"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6.0.10
    command: redis-server
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
volumes:
  redis_data:
