default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>_test

production:
  url: <%= ENV['DATABASE_URL'] %>
